---
# tasks file for docker-offline-deploy
- name: Creating Docker group
  group:
    name: docker
    gid: 55555
    state: present

- name: Creating Docker pack file folder
  file:
    path: /tmp/docker-offline
    state: directory
    owner: "phytsvh" 
    group: "phytsvh"
    mode: 0770
    recurse: yes

- name: Installing Docker locally - Red Hat 7.9
  block:
    - name: Unzipping Docker pack file to /tmp/docker-offline - Red Hat 7.9 installation
      unarchive:
        src: "/home/phytsvh/docker/docker-deploy-redhat-7.9.tar.gz"
        dest: /tmp/docker-offline
        owner: "phytsvh"
        group: "phytsvh"
        mode: 0770

    - name: Setting SELinux in permissive mode
      shell: setenforce 0

    - name: Installing Docker offline - Red Hat 7.9
      shell: yum localinstall -y *.rpm &> /dev/null
      args:
        warn: false
        chdir: /tmp/docker-offline
  become: true
  become_method: sudo
  # when: ansible_facts['distribution'] == "RedHat" and ansible_facts['distribution_version'] == "7.9"

- name: Performing common actions
  block:
    - name: Deploying custom configuration
      template:
        src: "{{ role_path }}/templates/daemon.json.j2"
        dest: /etc/docker/daemon.json
        owner: root
        group: docker
        mode: 0644

    - name: Restarting Docker service
      systemd:
        name: docker
        enabled: true
        daemon_reload: true
        state: restarted

    - name: "Adding phytsvh to docker group"
      user:
        name: "phytsvh"
        groups:
          - docker
        append: yes

- name: Installing miscellanea packages - Red Hat 7.9
  block:
    # - name: Creating Inotify temporary folder
    #   file:
    #     path: /tmp/inotify
    #     state: directory
    #     owner: "{{ hostvars[inventory_hostname]['USER'] }}"
    #     group: "{{ hostvars[inventory_hostname]['GROUP'] }}"
    #     mode: 0770

    # - name: Decompressing INotify
    #   unarchive:
    #     src: "{{ role_path }}/files/RedHat/inotify-redhat-7.tar.gz"
    #     dest: /tmp/inotify
    #     owner: "{{ hostvars[inventory_hostname]['USER'] }}"
    #     group: "{{ hostvars[inventory_hostname]['GROUP'] }}"
    #     mode: 0770
    
    # - name: Installing INotify
    #   shell: yum localinstall -y *.rpm &> /dev/null
    #   args:
    #     warn: false
    #     chdir: /tmp/inotify

    - name: Creating Dos2Unix temporary folder
      file:
        path: /tmp/dos2unix
        state: directory
        owner: "phytsvh"
        group: "phytsvh"
        mode: 0770
      
    - name: Decompressing Dos2Unix
      unarchive:
        src: "{{ role_path }}/files/RedHat/dos2unix-redhat-7.tar.gz"
        dest: /tmp/dos2unix
        owner: "{{ hostvars[inventory_hostname]['USER'] }}"
        group: "{{ hostvars[inventory_hostname]['GROUP'] }}"
        mode: 0770

    - name: Installing Dos2Unix
      shell: yum localinstall -y *.rpm &> /dev/null
      args:
        warn: false
        chdir: /tmp/dos2unix
  become: true
  become_method: sudo
  # when: ansible_facts['distribution'] == "RedHat" and ansible_facts['distribution_version'] == "7.9"

- name: Cleaning temporary folders - CentOS
  file: 
    path: /tmp/docker-offline
    state: absent
  become: true
  become_method: sudo
  when: ansible_facts['distribution'] == "CentOS"

- name: Cleaning temporary folders - Red Hat
  block:
    - name: Cleaning Docker install folders
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /tmp/docker-offline
        - /tmp/inotify
  become: true
  become_method: sudo
  when: ansible_facts['distribution'] == "RedHat"